const std = @import("std");
const png = @import("png.zig");
const tile = @import("tile.zig");
const metadata = @import("metadata.zig");

pub const CodegenOptions = struct {
    sprite_name: []const u8 = "sprite",
    bpp: png.BppMode = .auto,
    color_adjust: bool = false,
    palette_only: bool = false,
    no_palette: bool = false,
};

pub const CodegenError = error{
    ImageDecodeError,
    MetadataParseError,
    TileSliceError,
    WriteError,
    OutOfMemory,
    Unimplemented,
};

/// Formats a flat slice of 16-bit GBA BGR555 colors as hex literals with 8 items per line.
fn writeColorArray(writer: *std.Io.Writer, colors: []const u16, indent: []const u8) CodegenError!void {
    for (colors, 0..) |col, i| {
        if (i % 8 == 0) {
            writer.writeAll(indent) catch return error.WriteError;
        }
        writer.print("0x{X:0>4}, ", .{col}) catch return error.WriteError;
        if (i % 8 == 7 or i == colors.len - 1) {
            writer.writeAll("\n") catch return error.WriteError;
        }
    }
}

/// Emits a single 1D palette definition: `pub const <name> = [_]u16{ ... };`
fn writeSinglePalette(writer: *std.Io.Writer, name: []const u8, pal: []const u16) CodegenError!void {
    writer.print("pub const {s} = [_]u16{{\n", .{name}) catch return error.WriteError;
    try writeColorArray(writer, pal, "    ");
    writer.writeAll("};\n") catch return error.WriteError;
}

/// Emits a 16-bank 2D palette definition: `pub const palettes = [16][16]u16{ ... };`
fn writeBankedPalettes(writer: *std.Io.Writer, banks: *const [16][16]u16) CodegenError!void {
    writer.writeAll("pub const palettes = [16][16]u16{\n") catch return error.WriteError;
    for (banks, 0..) |bank, b_idx| {
        writer.print("    [_]u16{{ // Bank {}\n", .{b_idx}) catch return error.WriteError;
        try writeColorArray(writer, &bank, "        ");
        writer.writeAll("    },\n") catch return error.WriteError;
    }
    writer.writeAll("};\n\npub const raw_palette: [256]u16 = @bitCast(palettes);\n") catch return error.WriteError;
}

/// Dispatches palette emission based on the PaletteResult variant.
fn writePaletteResult(writer: *std.Io.Writer, pal_res: png.PaletteResult) CodegenError!void {
    switch (pal_res) {
        .bpp4 => |pal| try writeSinglePalette(writer, "palette", &pal),
        .bpp8 => |pal| try writeSinglePalette(writer, "palette", &pal),
        .bpp4x16 => |banks| try writeBankedPalettes(writer, &banks),
    }
}

const ShapeSizeName = struct {
    shape_name: []const u8,
    size_name: []const u8,
};

fn getHwShapeAndSize(w: u16, h: u16) ?ShapeSizeName {
    if (w == 8 and h == 8) return .{ .shape_name = "SQUARE", .size_name = "SIZE_0" };
    if (w == 16 and h == 16) return .{ .shape_name = "SQUARE", .size_name = "SIZE_1" };
    if (w == 32 and h == 32) return .{ .shape_name = "SQUARE", .size_name = "SIZE_2" };
    if (w == 64 and h == 64) return .{ .shape_name = "SQUARE", .size_name = "SIZE_3" };

    if (w == 16 and h == 8) return .{ .shape_name = "HORIZONTAL", .size_name = "SIZE_0" };
    if (w == 32 and h == 8) return .{ .shape_name = "HORIZONTAL", .size_name = "SIZE_1" };
    if (w == 32 and h == 16) return .{ .shape_name = "HORIZONTAL", .size_name = "SIZE_2" };
    if (w == 64 and h == 32) return .{ .shape_name = "HORIZONTAL", .size_name = "SIZE_3" };

    if (w == 8 and h == 16) return .{ .shape_name = "VERTICAL", .size_name = "SIZE_0" };
    if (w == 8 and h == 32) return .{ .shape_name = "VERTICAL", .size_name = "SIZE_1" };
    if (w == 16 and h == 32) return .{ .shape_name = "VERTICAL", .size_name = "SIZE_2" };
    if (w == 32 and h == 64) return .{ .shape_name = "VERTICAL", .size_name = "SIZE_3" };

    return null;
}

fn writeTileByteSlice(writer: *std.Io.Writer, bytes: []const u8, indent: []const u8) CodegenError!void {
    for (bytes, 0..) |b, i| {
        if (i % 16 == 0) {
            writer.writeAll(indent) catch return error.WriteError;
        }
        writer.print("0x{X:0>2}, ", .{b}) catch return error.WriteError;
        if (i % 16 == 15 or i == bytes.len - 1) {
            writer.writeAll("\n") catch return error.WriteError;
        }
    }
}

/// Generates full, type-safe Zig source code from PNG and JSON asset bytes.
pub fn generateZigSource(
    allocator: std.mem.Allocator,
    png_bytes: []const u8,
    json_bytes: ?[]const u8,
    options: CodegenOptions,
) CodegenError![]u8 {
    // 1. Extract palette
    const pal_res = png.extractPalette(png_bytes, .{
        .mode = options.bpp,
        .color_adjust = options.color_adjust,
    }) catch return error.ImageDecodeError;

    var aw: std.Io.Writer.Allocating = .init(allocator);
    defer aw.deinit();
    var writer = &aw.writer;

    writer.writeAll("// Generated by zurag - DO NOT EDIT MANUALLY\n") catch return error.WriteError;
    writer.writeAll("const std = @import(\"std\");\n") catch return error.WriteError;
    writer.writeAll("const engine = @import(\"zamgba-engine\");\n") catch return error.WriteError;
    writer.writeAll("const hal = @import(\"zamgba-hal\");\n\n") catch return error.WriteError;

    // 2. Handle palette-only mode
    if (options.palette_only) {
        try writePaletteResult(writer, pal_res);
        return allocator.dupe(u8, aw.written()) catch return error.OutOfMemory;
    }

    // 3. Full Sprite Mode: Parse Metadata
    const json_content = json_bytes orelse return error.MetadataParseError;
    var meta = metadata.parseMetadata(allocator, json_content, .auto) catch return error.MetadataParseError;
    defer meta.deinit();

    if (meta.frames.len == 0) {
        return error.MetadataParseError;
    }

    // 4. Decompress PNG pixels
    var img = png.decompressIndexedPixels(allocator, png_bytes) catch return error.ImageDecodeError;
    defer img.deinit();

    // 5. Slice all frames into GBA tiles
    const effective_bpp: png.BppMode = switch (pal_res) {
        .bpp4 => .bpp4,
        .bpp4x16 => .bpp4x16,
        .bpp8 => .bpp8,
    };

    var sliced_frames = allocator.alloc(tile.SlicedFrame, meta.frames.len) catch return error.OutOfMemory;
    defer {
        for (sliced_frames) |*sf| sf.deinit();
        allocator.free(sliced_frames);
    }

    for (meta.frames, 0..) |frame, i| {
        sliced_frames[i] = tile.sliceSpriteFrame(allocator, &img, frame.rect, effective_bpp) catch return error.TileSliceError;
    }

    const frame0 = meta.frames[0];
    const shape_size = getHwShapeAndSize(@intCast(frame0.rect.w), @intCast(frame0.rect.h)) orelse ShapeSizeName{
        .shape_name = "SQUARE",
        .size_name = "SIZE_0",
    };

    const bpp_enum_str = if (effective_bpp == .bpp8) ".bpp8" else ".bpp4";
    const frame_bytes_len = sliced_frames[0].bytes.len;

    // ==========================================
    // Emit Metadata & Constants
    // ==========================================
    writer.print("pub const name = \"{s}\";\n", .{options.sprite_name}) catch return error.WriteError;
    writer.print("pub const width: u16 = {};\n", .{frame0.rect.w}) catch return error.WriteError;
    writer.print("pub const height: u16 = {};\n", .{frame0.rect.h}) catch return error.WriteError;
    writer.print("pub const frame_count: u16 = {};\n", .{meta.frames.len}) catch return error.WriteError;
    writer.print("pub const tile_count_per_frame: u16 = {};\n", .{sliced_frames[0].tile_count}) catch return error.WriteError;
    writer.print("pub const bpp_mode: hal.specs.BppMode = {s};\n", .{bpp_enum_str}) catch return error.WriteError;
    writer.print("pub const shape: u16 = hal.oam.Shape.{s};\n", .{shape_size.shape_name}) catch return error.WriteError;
    writer.print("pub const size: u16 = hal.oam.Size.{s};\n", .{shape_size.size_name}) catch return error.WriteError;
    writer.print("pub const default_palette_bank: u8 = {};\n\n", .{sliced_frames[0].detected_bank}) catch return error.WriteError;

    // ==========================================
    // Emit Palette (if not suppressed by --no-palette)
    // ==========================================
    if (!options.no_palette) {
        try writePaletteResult(writer, pal_res);
        writer.writeAll("\n") catch return error.WriteError;
    }

    // ==========================================
    // Emit Frame Durations
    // ==========================================
    writer.print("pub const frame_durations_ms: [{}]u16 = [_]u16{{\n    ", .{meta.frames.len}) catch return error.WriteError;
    for (meta.frames) |frame| {
        writer.print("{}, ", .{frame.duration_ms}) catch return error.WriteError;
    }
    writer.writeAll("\n};\n\n") catch return error.WriteError;

    // ==========================================
    // Emit Frame Banks
    // ==========================================
    writer.print("pub const frame_banks: [{}]u8 = [_]u8{{\n    ", .{sliced_frames.len}) catch return error.WriteError;
    for (sliced_frames) |sf| {
        writer.print("{}, ", .{sf.detected_bank}) catch return error.WriteError;
    }
    writer.writeAll("\n};\n\n") catch return error.WriteError;

    // ==========================================
    // Emit Frame Tiles (ROM arrays)
    // ==========================================
    writer.print("pub const frame_tiles: [{}][{}]u8 = [{}][{}]u8{{\n", .{ meta.frames.len, frame_bytes_len, meta.frames.len, frame_bytes_len }) catch return error.WriteError;
    for (sliced_frames, 0..) |sf, f_idx| {
        writer.print("    [_]u8{{ // Frame {}\n", .{f_idx}) catch return error.WriteError;
        try writeTileByteSlice(writer, sf.bytes, "        ");
        writer.writeAll("    },\n") catch return error.WriteError;
    }
    writer.writeAll("};\n\n") catch return error.WriteError;
    writer.writeAll("pub const raw_tiles: []const u8 = std.mem.sliceAsBytes(&frame_tiles);\n\n") catch return error.WriteError;

    // ==========================================
    // Emit Animation Tags
    // ==========================================
    writer.print("pub const tags: [{}]engine.AnimationTag = [_]engine.AnimationTag{{\n", .{meta.tags.len}) catch return error.WriteError;
    for (meta.tags) |tag| {
        const dir_str = switch (tag.direction) {
            .forward => ".forward",
            .reverse => ".reverse",
            .pingpong => ".pingpong",
        };
        writer.print("    .{{ .name = \"{s}\", .from_frame = {}, .to_frame = {}, .direction = {s} }},\n", .{ tag.name, tag.from, tag.to, dir_str }) catch return error.WriteError;
    }
    writer.writeAll("};\n\n") catch return error.WriteError;

    // ==========================================
    // Emit Unified SpriteSheet Descriptor
    // ==========================================
    const pal_ptr_str = if (!options.no_palette) switch (pal_res) {
        .bpp4x16 => "&raw_palette",
        else => "&palette",
    } else "null";

    writer.writeAll("pub const sheet: engine.SpriteSheet = .{\n") catch return error.WriteError;
    writer.writeAll("    .bpp = bpp_mode,\n") catch return error.WriteError;
    writer.writeAll("    .width = width,\n") catch return error.WriteError;
    writer.writeAll("    .height = height,\n") catch return error.WriteError;
    writer.writeAll("    .tile_count_per_frame = tile_count_per_frame,\n") catch return error.WriteError;
    writer.writeAll("    .frame_count = frame_count,\n") catch return error.WriteError;
    writer.print("    .palette = {s},\n", .{pal_ptr_str}) catch return error.WriteError;
    writer.writeAll("    .tiles = raw_tiles,\n") catch return error.WriteError;
    writer.writeAll("    .durations_ms = &frame_durations_ms,\n") catch return error.WriteError;
    writer.writeAll("    .tags = &tags,\n") catch return error.WriteError;
    writer.writeAll("};\n") catch return error.WriteError;

    return allocator.dupe(u8, aw.written()) catch return error.OutOfMemory;
}

// ====================================================================
// Unit Tests for Code Generator (TDD Red Phase)
// ====================================================================

test "GEN001: generateZigSource for palette-only mode" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_pal16, null, .{
        .palette_only = true,
        .bpp = .bpp4,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palette = [_]u16{") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_tiles") == null);
}

test "GEN002: generateZigSource full sprite with real flying broom asset" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_broom, test_assets.json_broom, .{
        .sprite_name = "tsetseg_flying",
        .bpp = .bpp8,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const width: u16 = 32;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const height: u16 = 32;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_count: u16 = 8;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const tile_count_per_frame: u16 = 16;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"flying\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_tiles") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const raw_tiles") != null);
}

test "GEN003: generateZigSource 4x16 banked mode syntax" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_pal256, null, .{
        .palette_only = true,
        .bpp = .bpp4x16,
    });
    defer std.testing.allocator.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palettes = [16][16]u16{") != null);
}

test "GEN004: generateZigSource error when missing json in full sprite mode" {
    const test_assets = @import("test_palettes");
    try std.testing.expectError(error.MetadataParseError, generateZigSource(std.testing.allocator, test_assets.png_broom, null, .{
        .palette_only = false,
    }));
}

test "GEN005: generateZigSource with --no-palette omits palette definition" {
    const test_assets = @import("test_palettes");
    const out = try generateZigSource(std.testing.allocator, test_assets.png_broom, test_assets.json_broom, .{
        .sprite_name = "tsetseg_flying",
        .bpp = .bpp8,
        .no_palette = true,
    });
    defer std.testing.allocator.free(out);

    // Frame tiles are generated, but palette definition is omitted
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const frame_tiles") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const palette: [") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".palette = null") != null);
}

test "GEN006: getHwShapeAndSize maps all valid GBA OBJ dimensions and rejects invalid" {
    // Square
    const s0 = getHwShapeAndSize(8, 8).?;
    try std.testing.expectEqualStrings("SQUARE", s0.shape_name);
    try std.testing.expectEqualStrings("SIZE_0", s0.size_name);
    const s1 = getHwShapeAndSize(16, 16).?;
    try std.testing.expectEqualStrings("SQUARE", s1.shape_name);
    try std.testing.expectEqualStrings("SIZE_1", s1.size_name);
    const s2 = getHwShapeAndSize(32, 32).?;
    try std.testing.expectEqualStrings("SQUARE", s2.shape_name);
    try std.testing.expectEqualStrings("SIZE_2", s2.size_name);
    const s3 = getHwShapeAndSize(64, 64).?;
    try std.testing.expectEqualStrings("SQUARE", s3.shape_name);
    try std.testing.expectEqualStrings("SIZE_3", s3.size_name);

    // Horizontal
    const h0 = getHwShapeAndSize(16, 8).?;
    try std.testing.expectEqualStrings("HORIZONTAL", h0.shape_name);
    try std.testing.expectEqualStrings("SIZE_0", h0.size_name);
    const h1 = getHwShapeAndSize(32, 8).?;
    try std.testing.expectEqualStrings("HORIZONTAL", h1.shape_name);
    try std.testing.expectEqualStrings("SIZE_1", h1.size_name);
    const h2 = getHwShapeAndSize(32, 16).?;
    try std.testing.expectEqualStrings("HORIZONTAL", h2.shape_name);
    try std.testing.expectEqualStrings("SIZE_2", h2.size_name);
    const h3 = getHwShapeAndSize(64, 32).?;
    try std.testing.expectEqualStrings("HORIZONTAL", h3.shape_name);
    try std.testing.expectEqualStrings("SIZE_3", h3.size_name);

    // Vertical
    const v0 = getHwShapeAndSize(8, 16).?;
    try std.testing.expectEqualStrings("VERTICAL", v0.shape_name);
    try std.testing.expectEqualStrings("SIZE_0", v0.size_name);
    const v1 = getHwShapeAndSize(8, 32).?;
    try std.testing.expectEqualStrings("VERTICAL", v1.shape_name);
    try std.testing.expectEqualStrings("SIZE_1", v1.size_name);
    const v2 = getHwShapeAndSize(16, 32).?;
    try std.testing.expectEqualStrings("VERTICAL", v2.shape_name);
    try std.testing.expectEqualStrings("SIZE_2", v2.size_name);
    const v3 = getHwShapeAndSize(32, 64).?;
    try std.testing.expectEqualStrings("VERTICAL", v3.shape_name);
    try std.testing.expectEqualStrings("SIZE_3", v3.size_name);

    // Invalid
    try std.testing.expect(getHwShapeAndSize(10, 10) == null);
    try std.testing.expect(getHwShapeAndSize(8, 64) == null);
    try std.testing.expect(getHwShapeAndSize(128, 128) == null);
}
